package com.securityx.modelfeature.auth;

/**
 * Created by sachinkapse on 24/05/16.
 */

import com.fasterxml.jackson.annotation.JsonProperty;
import org.hibernate.validator.constraints.NotEmpty;

public class User {

    public static final String ROLE_ADMIN = "admin";
    public static final String ROLE_VIEWER = "viewer";

    public enum USER_TYPE {
        NORMAL,
        GENERATED,
        ALL
    }

    @NotEmpty
    @JsonProperty
    private String username;

    @NotEmpty
    @JsonProperty
    private String password;

    //@NotEmpty
    @JsonProperty
    private String displayName;

    //@NotEmpty
    @JsonProperty
    private String userRole;

    @JsonProperty
    private Boolean activeStatus;

    @JsonProperty
    private String createdForApp;

    @JsonProperty
    private Boolean isAutoGenerated;

    public String getUsername() {
        return username;
    }

    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return password;
    }

    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    public String getDisplayName() {
        return displayName;
    }

    public User setDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    public String getUserRole() {
        return userRole;
    }

    public User setUserRole(String userRole) {
        this.userRole = userRole;
        return this;
    }

    public Boolean getActiveStatus() {
        return activeStatus;
    }

    public void setActiveStatus(Boolean activeStatus) {
        this.activeStatus = activeStatus;
    }

    public Boolean getIsAutoGenerated() {
        return isAutoGenerated;
    }

    public void setIsAutoGenerated(Boolean isAutoGenerated) {
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getCreatedForApp() {
        return createdForApp;
    }

    public void setCreatedForApp(String createdForApp) {
        this.createdForApp = createdForApp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User)) return false;

        User that = (User) o;

        if (!getUsername().equals(that.getUsername())) return false;
        if (!getPassword().equals(that.getPassword())) return false;
        if (!getDisplayName().equals(that.getDisplayName())) return false;
        if (!getUserRole().equals(that.getUserRole())) return false;
        if (getActiveStatus().compareTo(that.getActiveStatus()) != 0) return false;
        if (!getCreatedForApp().equals(that.getCreatedForApp())) return false;
        if (getIsAutoGenerated().compareTo(that.getIsAutoGenerated()) != 0) return false;

        return true;
    }
}
