
package com.securityx.tds.taniumsoap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TaniumSOAPService", targetNamespace = "urn:TaniumSOAP", wsdlLocation = "file:/Users/suhasg/Downloads/console.wsdl")
public class TaniumSOAPService
    extends Service
{

    private final static URL TANIUMSOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.securityx.tds.taniumsoap.TaniumSOAPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.securityx.tds.taniumsoap.TaniumSOAPService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/suhasg/Downloads/console.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/suhasg/Downloads/console.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TANIUMSOAPSERVICE_WSDL_LOCATION = url;
    }

    public TaniumSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaniumSOAPService() {
        super(TANIUMSOAPSERVICE_WSDL_LOCATION, new QName("urn:TaniumSOAP", "TaniumSOAPService"));
    }

    /**
     * 
     * @return
     *     returns TaniumSOAPPort
     */
    @WebEndpoint(name = "TaniumSOAPPort")
    public TaniumSOAPPort getTaniumSOAPPort() {
        return super.getPort(new QName("urn:TaniumSOAP", "TaniumSOAPPort"), TaniumSOAPPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaniumSOAPPort
     */
    @WebEndpoint(name = "TaniumSOAPPort")
    public TaniumSOAPPort getTaniumSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:TaniumSOAP", "TaniumSOAPPort"), TaniumSOAPPort.class, features);
    }

}
