# this is a piece of a fuller script, generated by ../fpm-it.sh
# if ^ is not the first line, ignore this.

# SVC_USER=youknowho
# SVC_HOME=svc...home.
# so cheesy.

/usr/bin/getent group "$SVC_USER" || /usr/sbin/groupadd -r "$SVC_USER"
/usr/bin/getent passwd "$SVC_USER" || /usr/sbin/useradd -d "$SVC_HOME" -r "$SVC_USER" -g "$SVC_USER"

if [[ ! -e $E8_LOG_DIR ]]
then
	mkdir -p $E8_LOG_DIR
fi

chown $SVC_USER:$SVC_USER $E8_LOG_DIR


